algoritmo "Teste_variaveis"
// Função : Testar variaveis
// Autor :
// Data : 08/04/2022
// Seção de Declarações 
var
   nome : caracter
   idade : inteiro
   sexo : caracter

inicio
// Seção de Comandos
   escreva("Digite seu nome:")
   leia(nome)
   escreva("Digite sua idade:")
   leia(idade)
   escreva("digite seu sexo:")
   leia(sexo)
   
   escreva("Seu nome e: ")
   escreval(nome)
   
   escreva("Sua Idade e: ")
   escreval(idade)
   escreva("Seu sexo e: ")
   escreval(sexo)
fimalgoritmo
