CREATE USER 'MONITOR' IDENTIFIED BY '1234';
GRANT INSERT, SELECT, UPDATE, DELETE ON exercicio.aluno TO MONITOR;

SHOW GRANTS FOR MONITOR;

CREATE USER 'PROFESSOR' IDENTIFIED BY '5678';
GRANT ALL PRIVILEGES ON *.* TO 'PROFESSOR';

SHOW GRANTS FOR PROFESSOR;

REVOKE INSERT ON exercicio.aluno FROM 'MONITOR';

SHOW GRANTS FOR MONITOR;

REVOKE CREATE, DROP ON *.* FROM 'PROFESSOR';

SHOW GRANTS FOR PROFESSOR;

