-- MySQL Script generated by MySQL Workbench
-- Mon May 30 16:31:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituicao` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `Instituicao_codigo` INT NOT NULL,
  PRIMARY KEY (`idAutor`, `Instituicao_codigo`),
  INDEX `fk_Autor_Instituicao1_idx` (`Instituicao_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_Instituicao1`
    FOREIGN KEY (`Instituicao_codigo`)
    REFERENCES `mydb`.`Instituicao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artigos` (
  `idIdentificacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `dataAp` DATE NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idIdentificacao`, `Autor_idAutor`),
  INDEX `fk_Artigos_Autor_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Artigos_Autor`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transferencia` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `dataTr` DATE NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participantes` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Transferencia_numero` INT NOT NULL,
  PRIMARY KEY (`codigo`, `Transferencia_numero`),
  INDEX `fk_Participantes_Transferencia1_idx` (`Transferencia_numero` ASC) VISIBLE,
  CONSTRAINT `fk_Participantes_Transferencia1`
    FOREIGN KEY (`Transferencia_numero`)
    REFERENCES `mydb`.`Transferencia` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assiste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assiste` (
  `Artigos_idIdentificacao` INT NOT NULL,
  `Participantes_codigo` INT NOT NULL,
  PRIMARY KEY (`Artigos_idIdentificacao`, `Participantes_codigo`),
  INDEX `fk_Artigos_has_Participantes_Participantes1_idx` (`Participantes_codigo` ASC) VISIBLE,
  INDEX `fk_Artigos_has_Participantes_Artigos1_idx` (`Artigos_idIdentificacao` ASC) VISIBLE,
  CONSTRAINT `fk_Artigos_has_Participantes_Artigos1`
    FOREIGN KEY (`Artigos_idIdentificacao`)
    REFERENCES `mydb`.`Artigos` (`idIdentificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artigos_has_Participantes_Participantes1`
    FOREIGN KEY (`Participantes_codigo`)
    REFERENCES `mydb`.`Participantes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
